name: Trivy CVE Dependency Scanner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # schedule:
   #  - cron: "*/5 * * * *"
  # allow reuse of this workflow in other repos
  workflow_call:

jobs:
  build:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.4.0
      
      - name: Run Trivy vulnerability scanner in repo mode
        # https://github.com/marketplace/actions/aqua-security-trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: false
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
